# -*- coding: utf-8 -*-
"""오픈소스_데이터_분석_3강.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WRzNtWjbpduAJNAG3yl62CkrfVwxgmtg

# 오픈소스 기반 데이터 분석 3강 - 데이터 분석을 위한 파이썬 2

## 3-1 언패킹
"""

coordinates = (10, 20)
x,y = coordinates
# 튜플 언패킹
print(f'x좌표: {x}, y좌표: {y}')

rgb = [255, 128, 0]
# 리스트 언패킹
red, green, blue = rgb
print(f'빨강: {red}, 초록: {green}, 파랑: {blue}')

word = 'ABC'
# 문자열 언패킹
first, second, third = word
print(f'첫 번째 문자: {first}, 두 번째 문자: {second}, 세 번째 문자: {third}')

def get_dataset_stats(values):
  return min(values), max(values), sum(values) / len(values)

data = [12, 8, 21, 17, 5, 32, 14]

# 함수값 return 언패킹
minimum, maximum, average = get_dataset_stats(data)
print(f'최솟값: {minimum}, 최댓값: {maximum}, 평균: {average:.2f}')

student_scores = [
    ('김철수', 85, 92, 78),
    ('이영희', 92, 88, 95),
    ('박지민', 75, 83, 90)
]

# 반복문에서 언패킹 사용
for name,database, python, cloud in student_scores :
  average = (database + python + cloud) / 3
  print(f'{name}의 평균 점수: {average:.1f}')

monthly_sales = [1200, 1350, 1420, 1500, 1300, 1580, 1620, 1700, 1800, 1850, 1900, 2000]

# 1월, 2월 및 나머지 월 매출액
first, second, *remaining  = monthly_sales
print(f'1월 판매액: {first}')
print(f'2월 판매액: {second}')
print(f'나머지 월 판매액: {remaining}')

# 1월, 12월 및 나머지 월 매출액
first, *middle, last = monthly_sales
print(f'첫 달(1월) 판매액: {first}')
print(f'마지막 달(12월) 판매액: {last}')
print(f'중간 달(2~11월)의 판매액: {middle}')

"""## 3-5 언더스코어"""

students = [
    (20251234, '김철수', '컴퓨터과학', 2, 3.8),
    (20265678, '이영희', '생활과학부', 3, 4.2),
    (20243456, '박민수', '사회복지학과', 1, 3.5)
]

# 이름 및 성적 만 출력
for _,name,_,_,grade in students :
    print(f'{name}의 성적: {grade}')

def get_coordinates( ):
    return (10, 20, 30)
# 함수 return 값 언더스코어 사용
_, y, _= get_coordinates()
print(y)

"""## 3-2 예외 처리"""

number = int(input('정수를 입력하세요: '))
result = 10 / number
print(f'결과: {result}')

number = int(input('정수를 입력하세요: '))

# try 문
try :
    result = 10 / number
    print(f'결과: {result}')
# except 문
except :
    print('0으로 나눌 수 없습니다.')

# try 문
try :
    number = int(input('숫자를 입력하세요: '))
    result = 10 / number
    print(f'결과: {result}')
# except 문 1
except 1  :
    print('유효한 숫자를 입력해야 합니다.')
# except 문 2
except 2 :
    print('0으로 나눌 수 없습니다.')

# try 문
try :
    file = open('data.csv', 'r')
    content = file.read( )
    print(content)

# except 문
except  :
    print('파일을 찾을 수 없습니다.')

# fianlly 블럭
finally :
    print('파일 작업 종료.')
    file.close( )

"""## 3-3 함수형 프로그래밍"""

employees = {
    '이지혜': 3000000,
    '구민준': 5000000,
    '방서연': 4100000
}

# 함수 정의: salary * 1.1
adjust_salary=lambda salary: salary *1.1
# 급여 인상
updated_salary = {name : adjust_salary(salary) for name, salary in employees.items()}
print(updated_salary)

temperature_celsius = [25.6, 27.8, 30.5, 22.3, 28.9, 31.2, 24.7]

# 함수 정의: 섭씨 -> 화씨
cel_to_fah = lambda  c: (c*9/5) +35
# 온도 변환
temperature_fahrenheit = list(map(cel_to_fah, temperature_celsius))
print('섭씨 온도 데이터:', temperature_celsius)
print('화씨 온도로 변환:', temperature_fahrenheit)

words = ['python', 'data', 'analysis']

# 함수 정의 및 대문자화


print(uppercase_words)

employees = [
    {'name': '김지원', 'salary': 3700000},
    {'name': '박민준', 'salary': 7000000},
    {'name': '이서연', 'salary': 4400000},
    {'name': '정현우', 'salary': 3500000}
]

# salary * 1.1


print('\n급여 인상 후:')

for emp in updated_employees:
    print(f'{emp['name']}: {int(emp['salary']):,}원')

numbers = [10, 15, 20, 25, 30]

# 짝수 필터링


print(even_numbers)

osda_students = [
    {'name': '김지원', 'score': 85},
    {'name': '이민준', 'score': 65},
    {'name': '박서연', 'score': 90},
    {'name': '정현우', 'score': 55},
    {'name': '최예은', 'score': 78}
]

# 70점 이상 학생 목록 생성
passed_students = list (filter (lambda student : student["score"]>=70, osda_students))

for student in passed_students:
    print(f'이름: {student["name"]}, 점수: {student["score"]}')

from functools import reduce
numbers = [3, 7, 2, 9, 5]
# 최대값 생성
max_value = reduce (lambda x, y : x if x>y else y, numbers)
" x, y 중에 x가 크면 x를 남기고 y가 크면 y를 남겨라"

print(max_value)