# -*- coding: utf-8 -*-
"""오픈소스_데이터_분석_2강.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJEs_042ee_HlRea7ADYpHLLTMMGPWAs

# 오픈소스 기반 데이터 분석 2강 - 데이터 분석을 위한 파이썬 1

## 2-1 리스트 슬라이싱
"""



numbers = [10, 20, 30, 40, 50, 60, 70]
# 첫 4개의 원소 출력
first_four=numbers[0:4]
print(first_four)
# 뒤 3개의 원소를 출력
last_three=numbers[-3:7]
print(last_three)

numbers = [10, 20, 30, 40, 50, 60, 70]
# 홀수번째 항목 출력
every_other_list=numbers[:7:2]
print(every_other_list)
# 역순 출력
reverse_list=numbers[::-1]
print(reverse_list)

matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

# 첫 두 행 출력
first_two_rows=matrix[0:2]
print(first_two_rows)

# 첫 두 열 출력
first_two_columns=[row[0:2] for row in matrix]

print(first_two_columns)

"""## 2-2 리스트 컴프리헨션"""

numbers = [ ]

# 0 ~ 4 포함 리스트 생성
numbers=[i for i in range(5)]
print(numbers)

numbers = [1, 2, 3, 4, 5]
squares = [ ]

# numbers의 모든 항목의 값을 제곱한 리스트
"""for num in numbers:
  squares.append(num ** 2)"""
squares = [num**2 for num  in numbers]
print(squares)

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = [ ]

# 짝수만 추출한 리스트
for num in numbers:
    if num % 2 == 0:
        even_numbers.append(num)
even_numbers= [num for num in numbers if num % 2 == 0]
print(even_numbers)

list1 = ['사과', '복숭아', '바나나']
list2 = ['주스', '잼', '통조림']
pairs = [ ]

# 두 리스트에 포함되 모든 원소를 조합한 투플의 리스트 생성
"""for fruit in list1:
    for product in list2:
        pairs.append((fruit, product))"""
pairs = [(fruit, product) for fruit in list1 for product in list2]
"(튜플식)+ 중첩된 for문"
print(pairs)

squares = { }

# 딕셔너리 생성
for i in range(5):
    squares[i] = i ** 2
spares = {i : i**2 for i in range(5)}
print(squares) a

# method items의 역할과 목적 기억하기
city_population = {
    '서울': 957, '부산': 339, '인천': 294, '대구': 242, '광주': 145, '대전': 147,
    '울산': 114, '세종': 36, '수원': 115, '창원': 103, '고양': 105, '용인': 108, '성남': 94
}
large_cities= {city:pop for city, pop in city_population.items() if pop >=200}
# 인구 200만명 이상의 도시 리스트
print(large_cities)

# 인구 300만 이상 및 이름에 '산'이 포함된 도시 리스트
large_short_name_cities ={city:pop for city, pop in city_population.items() if pop >=300 and '산' in city}
print(large_short_name_cities)

"""## 2-3 문자열 형식화"""

name = '홍길동'
age = 30
salary = 3500000
tax_rate = 0.1

# C 스타일 문자열 포매팅
# 이름, 나이, 월급 출력
basic_format='이름 : %s, 나이 : %f, 월급 :%d' %(name,age,salary)
# 직원이름, 나이, 세후 월급 출력
basic_format ='이름 : %s, 나이 : %f, 월급 : %d원' % (name, age, salary-(salary*tax_rate))
# 직원이름, 나이, 월급, 세금, 실수령액 추력
basic_format ='이름 : %s, 나이 : %i, 월급 : %d원, 세금 : %i, 실수령액 : %d' %(name, age,salary, salary/10 *tax_rate, salary-(salary/10*tax_rate))
print(basic_format)

name = '홍길동'
age = 30
salary = 3500000
tax_rate = 0.1

# str.format 문자열 포매팅
# 이름, 나이, 월급 출력
basic_format='이름 : {0}, 나이 : {1}, 월급 : {2}'.format(name, age, salary)
# 직원이름, 나이, 세후 월급 출력
basic_format='직원이름 : {0}, 나이 : {1}, 세후 월급 : {2}'.format(name, age, salary-salary*tax_rate)
# 직원이름, 나이, 월급, 세금, 실수령액 추력
basic_format = '직원이름 : {0}, 나이 : {2}, 월급 : {1}, 세금 :{3}, 실수령액 :{4}'.format(name, salary, age, tax_rate*salary,salary-salary*tax_rate )

print(basic_format)

name = '홍길동'
age = 30
salary = 3500000
tax_rate = 0.1

# f-문자열 포매팅
# 이름, 나이, 월급 출력
basic_format= f'이름 : {name}, 나이 : {age}, 월급 : {salary}'
# 직원이름, 나이, 세후 월급 출력
basic_format= f'이름 : {name}, 나이 : {age}, 세후 월급 : {salary-salary*tax_rate}'
# 직원이름, 나이, 월급, 세금, 실수령액 추력
basic_format= f'이름 : {name}, 나이 : {age}, 월급 : {salary}, 세금 :{salary*tax_rate}, 실수령액 : {salary-salary*tax_rate}'

print(basic_format)

"""## 2-4 컨텍스트 관리"""

# 파일 오픈 & 클로즈
with open('output.txt', 'w') as file_write :
    file_write.write ('Hello, world!')

# 복수개의 파일(읽기 & 쓰기) 관리

import urllib.request

# URL 연결 관리
('https://raw.githubusercontent.com/jaehwachung/Data-Analysis-with-Open-Source/refs/heads/main/Chapter%203/students.csv')
    data = response.read( ).decode('utf-8')

print(data)